[package]
name = "async-tungstenite"
description = "async-std binding for Tungstenite, the Lightweight stream-based WebSocket implementation"
categories = ["web-programming::websocket", "network-programming", "asynchronous", "concurrency"]
keywords = ["websocket", "io", "web"]
authors = ["Sebastian Dröge <sebastian@centricular.com>"]
license = "MIT"
homepage = "https://github.com/sdroege/async-tungstenite"
repository = "https://github.com/sdroege/async-tungstenite"
documentation = "https://docs.rs/async-tungstenite"
version = "0.2.1"
edition = "2018"

[features]
default = ["connect", "tls", "async_std_runtime"]
connect = ["stream"]
async_std_runtime = ["connect", "async-std"]
tls-base = ["stream"]
tls = ["async-tls", "tls-base"]
native-tls = ["async-native-tls", "real-native-tls", "tls-base", "tungstenite/tls"]
stream = []

[dependencies]
log = "0.4"
futures = "0.3"
pin-project = "0.4"

[dependencies.tungstenite]
version = "0.9.2"
default-features = false

[dependencies.async-std]
optional = true
version = "1.0"

[dependencies.async-tls]
optional = true
version = "0.6.0"

[dependencies.async-native-tls]
optional = true
version = "0.1.0"

[dependencies.real-native-tls]
optional = true
version = "0.2"
package = "native-tls"

[dev-dependencies]
url = "2.0.0"
env_logger = "0.7"
async-std = { version = "1.0", features = ["attributes"] }
